### ISSUE TITLE
Error: Unable to locate plugin velero.io/tardigrade

### ISSUE THREAD

**Issue by 0cwa** [storj/velero-plugin#19]
After installing I get a bunch of errors that all say something like:
```time="2022-06-01T04:39:42Z" level=error msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="unable to locate ObjectStore plugin named velero.io/tardigrade" logSource="pkg/controller/backup_sync_controller.go:175"```

**Comment by andy108369** [comment]
Had the same issue with velero helm-charts, solved by setting it in the `initContainers` as follows:

```
configuration:
  backupStorageLocation:
    bucket: <YOUR-BUCKET-NAME>
    name: default
    config:
      accessGrant: "<YOUR-STORJ-ACCESS-GRANT>"
  defaultVolumesToRestic: true
  provider: tardigrade
initContainers:
- image: storjlabs/velero-plugin
  name: tardigrade-velero-plugin
  volumeMounts:
  - mountPath: /target
    name: plugins
```
