### ISSUE TITLE
"An error occurred: gzip: invalid header" on velero backup logs

### ISSUE THREAD

**Issue by andy108369** [storj/velero-plugin#20]
Velero v1.9.1

Config:

```
configuration:
  backupStorageLocation:
    bucket: <YOUR-BUCKET-NAME>
    name: default
    config:
      accessGrant: "<YOUR-STORJ-ACCESS-GRANT>"
  defaultVolumesToRestic: true
  provider: tardigrade
initContainers:
- image: storjlabs/velero-plugin
  name: tardigrade-velero-plugin
  volumeMounts:
  - mountPath: /target
    name: plugins
```

Getting "An error occurred: gzip: invalid header" on `velero backup logs` command:

```
$ velero backup get
NAME                            STATUS            ERRORS   WARNINGS   CREATED                          EXPIRES   STORAGE LOCATION   SELECTOR
velero-default-20220913223032   PartiallyFailed   29       0          2022-09-14 00:30:32 +0200 CEST   29d       default            <none>

$ velero backup logs velero-default-20220913223032
An error occurred: gzip: invalid header
```

```
$ kubectl -n velero get backups.velero.io -o yaml
...
      helm.sh/chart: velero-2.31.6
...
    formatVersion: 1.1.0
    phase: PartiallyFailed
    progress:
      itemsBackedUp: 959
      totalItems: 959
...
```

```
$ kubectl -n velero get downloadrequests.velero.io
NAME                                                                 AGE
velero-default-20220913223032-139b3f2e-ee05-41f7-9a15-c04eae2078dd   4m17s
velero-default-20220913223032-845f3754-c7d2-4100-9c8e-20173d5aa8c2   3m30s
velero-default-20220913223032-dda4f869-ac45-49da-bdef-5280a8435ee0   2m6s
```

```
$ kubectl -n velero get downloadrequests.velero.io velero-default-20220913223032-dda4f869-ac45-49da-bdef-5280a8435ee0 -o yaml
...
spec:
  target:
    kind: BackupLog
    name: velero-default-20220913223032
status:
  downloadURL: https://link.tardigradeshare.io/1uMr.......PAk/my-bucket/backups%2Fvelero-default-20220913223032%2Fvelero-default-20220913223032-logs.gz
```

Downloading that link `https://link.tardigradeshare.io/1uMr.......PAk/my-bucket/backups%2Fvelero-default-20220913223032%2Fvelero-default-20220913223032-logs.gz` - brings the HTML page (not the .gz file) with the following contents (see the screenshot):

![image](https://user-images.githubusercontent.com/107317698/190021886-5436e8e1-32a6-4d01-a3fc-e77976bdf903.png)

Any pointers?
